name: Update Anime List

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:  

jobs:
  update-anime-list:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.11.0'  

    - name: Install Dependencies
      run: npm install  

    - name: Run Anime List
      run: node anime-list.js  

    - name: Pull latest changes from remote (avoid push rejection)
      run: |
        git pull origin master --rebase

    - name: Commit & Push changes to README.md
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update anime list in README" || echo "No changes to commit"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
